title: MAI HQ #name/website title
logo: #logo or photo here
theme: jekyll-theme-tactile
description: >
  Blogging the journey of becoming me.
google_analytics: #your google analytics tracking ID here
